### ISSUE TITLE
Binary overrides

### ISSUE THREAD

**Issue by aaronbell** [chiron-fonts/chiron-hei-hk-gf#1]
In reviewing the build system used for this font project, I noted that after building the font, a number of tables are overridden by binary data. Can you give information about the intention behind these overrides? Would it be possible to get the GSUB / GPOS data in a source, .fea format? Thanks!

**Comment by tamcy** [comment]
Hello! The font is derived from Noto Sans CJK/Source Han Sans, so I use [AFDKO](https://github.com/adobe-type-tools/afdko) as the building toolchain, which produces CFF2 OpenType `.otf` font.

Ideally, converting a CFF2 variable font to a TTF one should cost just a single command or script (something like `otf2ttf`), but turns out it isn't that straightforward. So the TTF font is produced with the following steps:

1. First, the master OTFs are generated using the master postscript files, the feature files, the cidfontinfo files, and so on.
2. The master OTFs are then used compiled to compile the OTF file using `buildcff2vf`. This variable otf is already a working one, but in CFF2 format.
3. The master OTFs are also converted to `.ufo` format using the `tx` command in AFDKO. 
4. Then a script is used to compile the `.ufo` masters to a TTF file. The script is adapted from https://github.com/adobe-fonts/source-han-sans/issues/297#issuecomment-975175400.
5. Finally, `sfntedit` is run to replace certain tables in the .TTF file with the .OTF ones.

The final step is needed because most font tables are missing in the `.ufo` masters produced by `tx` in step 3. So the `.ttf` is unusable without replacing those tables with the ones in the OTF generated in step 2.

I was unable to find any example of submission of CFF2 variable fonts, so this is what i tried to comply with the submission requirement. I'd be happy to also provide the sources (i.e. those in step 1 above) to give more transparency if allowed.

**Comment by tamcy** [comment]
@aaronbell Not sure if this is still on the radar and if there is still interest in it. Just want to let you know I've prepared some changes in [the ps-source branch](https://github.com/chiron-fonts/chiron-hei-hk-gf/tree/ps-source) which should give more transparency on what is happening under the hood, and may relieve some worry if there's any. We can move to this one if there's any help in bringing this to Google Fonts.

In this branch, the variable OTFs are first produced from the `.ps` files. This [build script](https://github.com/chiron-fonts/chiron-hei-hk-gf/blob/00964d40440c83f9d970b514c072a94da5332541/bin/build_google_font.sh) shows how the UFOs are produced, and how the font tables in the variable TTFs are replaced with the ones in the variable OTFs.
